title: "RengTech"
email: rengtech2020@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'rengtech'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-NHQ6Q8MQ3S

# Authors
authors:
  sal:
    name: Rengtech
    display_name: Rengtech
    avatar: 'assets/images/Rengtech.png'
    email: wowthemesnet@gmail.com
    web: https://rengtech.github.io
    twitter: https://twitter.com/Reengstuff
    description: "RengTech Youtube Channel"
  john:
    name: Rengtech
    display_name: Rengtech
    avatar: 'assets/images/Rengtech.png'
    email: wowthemesnet@gmail.com
    web: https://rengtech.github.io
    twitter: https://twitter.com/Reengstuff
    description: "RengTech Youtube Channel"

# Social
social:
  instagram: https://twitter.com/Reengstuff
  facebook: https://twitter.com/Reengstuff
  twitter: https://twitter.com/Reengstuff
  youtube: https://www.youtube.com/@rengtech/videos
# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives